version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  apiappshop:
    image: ${DOCKER_REGISTRY-}apiappshop
    build:
      context: .
      dockerfile: ApiAppShop/Dockerfile

