version: '3.4'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9001:80"

  apiappshop:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "9002:80" 
    depends_on:
    - mongodbcontainer

  mongodbcontainer:
    image: mongo    
    ports:
      - 27017:27017
